import { useEffect, useMemo, useState } from 'react';
import { Linking, Pressable, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Badge, Button, Card, Header, Loading, Page, ui } from '@/components/Ui';
import { useSchedule } from '@/api/hooks';
import type { EventItem } from '@/types';
import { colors } from '@/theme';
import { approximateMatchesMonth, conflictsWithEvent, describeEventTiming, eventDateLabel, eventPrecision, getEventTiming, hasCalendarPermission, isLikelySameEvent, loadDeviceCalendarSnapshot, type DeviceCalendarEvent } from '@/calendar';

const weekday=['월','화','수','목','금','토','일'];
function dayKey(value:Date|string){const d=value instanceof Date?value:new Date(value);if(Number.isNaN(d.getTime()))return '';return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function monthStart(d:Date){return new Date(d.getFullYear(),d.getMonth(),1);}
function monthEnd(d:Date){return new Date(d.getFullYear(),d.getMonth()+1,0,23,59,59,999);}
function shiftDay(d:Date,days:number){return new Date(d.getFullYear(),d.getMonth(),d.getDate()+days,12,0,0,0);}
function calendarGrid(month:Date){const first=monthStart(month),offset=(first.getDay()+6)%7,start=shiftDay(first,-offset);return Array.from({length:42},(_,i)=>shiftDay(start,i));}
function formatTime(value:string,allDay=false){if(allDay)return '하루 종일';const d=new Date(value);return Number.isNaN(d.getTime())?'시간 확인 필요':d.toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit',hour12:false});}
function keysForRange(startValue:string,endValue:string,allDay=false){const start=new Date(startValue),rawEnd=new Date(endValue);if(Number.isNaN(start.getTime())||Number.isNaN(rawEnd.getTime()))return [];const end=allDay&&rawEnd>start?new Date(rawEnd.getTime()-1):rawEnd;const out:string[]=[];let cur=new Date(start.getFullYear(),start.getMonth(),start.getDate(),12),last=new Date(end.getFullYear(),end.getMonth(),end.getDate(),12);for(let guard=0;cur<=last&&guard<370;guard++,cur=shiftDay(cur,1)){const k=dayKey(cur);if(k)out.push(k);}return out;}
function keysForDevFeed(event:EventItem){const timing=getEventTiming(event);if(!timing)return [];if(timing.durationDays>7){const first=dayKey(timing.start),last=dayKey(timing.displayEnd);return [...new Set([first,last].filter(Boolean))];}return keysForRange(timing.start.toISOString(),timing.end.toISOString(),timing.allDayLike);}
function addToMap<T>(map:Map<string,T[]>,keys:string[],item:T){for(const k of keys)map.set(k,[...(map.get(k)??[]),item]);}

export default function ScheduleScreen(){
  const schedule=useSchedule();const [month,setMonth]=useState(()=>monthStart(new Date()));const [selected,setSelected]=useState(()=>dayKey(new Date()));const [deviceEvents,setDeviceEvents]=useState<DeviceCalendarEvent[]>([]);const [permission,setPermission]=useState<'checking'|'granted'|'denied'>('checking');const [loading,setLoading]=useState(false);const [calendarCount,setCalendarCount]=useState(0);const [failedCount,setFailedCount]=useState(0);const [loadError,setLoadError]=useState<string|null>(null);const grid=useMemo(()=>calendarGrid(month),[month]);
  const allDevfeed=schedule.data?.items??[];const exactDevfeed=allDevfeed.filter(e=>eventPrecision(e)==='EXACT'&&Boolean(e.startDate));const approximateThisMonth=allDevfeed.filter(e=>approximateMatchesMonth(e,month));
  const load=async(request=false)=>{setLoading(true);setLoadError(null);try{const granted=await hasCalendarPermission(request);setPermission(granted?'granted':'denied');if(!granted){setDeviceEvents([]);setCalendarCount(0);setFailedCount(0);return;}const snapshot=await loadDeviceCalendarSnapshot(shiftDay(monthStart(month),-7),shiftDay(monthEnd(month),7),false);setDeviceEvents(snapshot.events);setCalendarCount(snapshot.calendarCount);setFailedCount(snapshot.failedCalendarCount);}catch(err){setDeviceEvents([]);setCalendarCount(0);setFailedCount(0);setLoadError(err instanceof Error?err.message:'기기 캘린더를 읽지 못했습니다.');}finally{setLoading(false);}};
  useEffect(()=>{void load(false);},[month]);
  const visibleDeviceEvents=useMemo(()=>deviceEvents.filter(item=>!allDevfeed.some(e=>isLikelySameEvent(e,item))),[deviceEvents,schedule.data]);
  const {devfeedByDay,deviceByDay}=useMemo(()=>{const d=new Map<string,EventItem[]>(),g=new Map<string,DeviceCalendarEvent[]>();for(const e of exactDevfeed)addToMap(d,keysForDevFeed(e),e);for(const e of visibleDeviceEvents)addToMap(g,keysForRange(e.startDate,e.endDate,e.allDay),e);return {devfeedByDay:d,deviceByDay:g};},[schedule.data,visibleDeviceEvents]);
  const dayDev=devfeedByDay.get(selected)??[],dayDevice=deviceByDay.get(selected)??[];const conflictMap=new Map<string,{minutes:number;approximate:number;count:number}>();for(const e of dayDev){const conflicts=conflictsWithEvent(e,deviceEvents);if(conflicts.length)conflictMap.set(e.id,{minutes:conflicts.filter(x=>!x.approximate).reduce((sum,x)=>sum+x.minutes,0),approximate:conflicts.filter(x=>x.approximate).length,count:conflicts.length});}const selectedDate=new Date(`${selected}T12:00:00`);
  return <Page>
    <Header title="일정" right={<Pressable onPress={()=>router.push('/settings')}><Text style={{fontSize:22}}>⚙️</Text></Pressable>} />
    <Card><Text style={ui.h2}>DevFeed + 휴대폰 캘린더</Text><Text style={ui.muted}>정확한 날짜가 확인된 행사만 달력 점과 충돌 계산에 사용합니다. ‘10월 중’ 같은 일정은 가짜 날짜로 펼치지 않습니다.</Text>{permission==='checking'&&<Text style={ui.muted}>캘린더 권한 확인 중…</Text>}{permission==='denied'&&<View style={{gap:8}}><Text style={ui.muted}>기기 일정을 같이 보려면 캘린더 접근 권한이 필요합니다.</Text><Button label="캘린더 접근 허용" onPress={()=>void load(true)}/><Button label="휴대폰 앱 설정 열기" variant="ghost" onPress={()=>void Linking.openSettings()}/></View>}{permission==='granted'&&!loadError&&<Text style={{color:colors.green,fontWeight:'800'}}>✓ 연결됨 · 캘린더 {calendarCount}개 · 일정 {deviceEvents.length}개</Text>}{failedCount>0&&<Text style={{color:colors.red,fontWeight:'800'}}>⚠ 일부 캘린더 {failedCount}개는 읽지 못해 건너뛰었습니다.</Text>}{loadError&&<View style={{gap:8}}><Text style={{color:colors.red,fontWeight:'800'}}>캘린더를 불러오지 못했습니다.</Text><Button label="다시 불러오기" variant="ghost" onPress={()=>void load(false)}/></View>}</Card>
    <Card><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><Pressable onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><Text style={ui.h2}>‹</Text></Pressable><Pressable onPress={()=>{const now=monthStart(new Date());setMonth(now);setSelected(dayKey(new Date()));}}><Text style={ui.h2}>{month.getFullYear()}년 {month.getMonth()+1}월</Text></Pressable><Pressable onPress={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><Text style={ui.h2}>›</Text></Pressable></View><View style={{flexDirection:'row'}}>{weekday.map(x=><Text key={x} style={{flex:1,textAlign:'center',color:colors.muted,fontSize:12,fontWeight:'800'}}>{x}</Text>)}</View><View style={{flexDirection:'row',flexWrap:'wrap'}}>{grid.map(d=>{const k=dayKey(d),inMonth=d.getMonth()===month.getMonth(),active=k===selected,dc=devfeedByDay.get(k)?.length??0,gc=deviceByDay.get(k)?.length??0;return <Pressable key={k} onPress={()=>setSelected(k)} style={{width:'14.2857%',paddingVertical:7,alignItems:'center',opacity:inMonth?1:.35}}><View style={{width:34,height:34,borderRadius:17,alignItems:'center',justifyContent:'center',backgroundColor:active?colors.text:'transparent'}}><Text style={{color:active?colors.bg:colors.text,fontWeight:'800'}}>{d.getDate()}</Text></View><View style={{height:8,flexDirection:'row',gap:2,alignItems:'center'}}>{dc>0&&<View style={{width:5,height:5,borderRadius:3,backgroundColor:colors.accent}}/>}{gc>0&&<View style={{width:5,height:5,borderRadius:3,backgroundColor:colors.green}}/>}</View></Pressable>})}</View><View style={ui.row}><Badge>● DevFeed</Badge><Badge>● 기기 캘린더</Badge><Pressable onPress={()=>void load(false)}><Badge>↻ 새로고침</Badge></Pressable></View></Card>
    {approximateThisMonth.length>0&&<View><Text style={ui.h2}>📌 {month.getMonth()+1}월 중 · 날짜 미정</Text>{approximateThisMonth.map(e=>{const legacy=deviceEvents.some(x=>isLikelySameEvent(e,x));return <Card key={`a-${e.id}`} onPress={()=>router.push(`/event/${e.id}`)}><View style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><Text style={[ui.h2,{flex:1}]}>{e.title}</Text><Badge>날짜 미정</Badge></View><Text style={ui.body}>📅 {eventDateLabel(e)}</Text><Text style={ui.muted}>정확한 날짜 공개 전까지 달력 점·시간 충돌 계산에서 제외</Text>{legacy&&<Text style={{color:colors.red,fontWeight:'800'}}>⚠ 예전에 추가한 임시 기기 캘린더 일정은 직접 삭제하는 것을 권장해요.</Text>}</Card>})}</View>}
    <Text style={ui.h2}>{Number.isNaN(selectedDate.getTime())?selected:selectedDate.toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'long'})}</Text>{(schedule.isLoading||loading)&&<Loading/>}{schedule.error&&<Card><Text style={{color:colors.red,fontWeight:'800'}}>DevFeed 참가 일정을 불러오지 못했습니다.</Text></Card>}{dayDev.length===0&&dayDevice.length===0&&!loading&&<Card><Text style={ui.muted}>이 날은 표시할 일정이 없습니다.</Text></Card>}
    {dayDev.map(e=>{const conflict=conflictMap.get(e.id),alsoOnDevice=deviceEvents.some(x=>isLikelySameEvent(e,x));return <Card key={`d-${e.id}`} onPress={()=>router.push(`/event/${e.id}`)}><View style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><Text style={[ui.h2,{flex:1}]}>{e.title}</Text><Badge>DevFeed</Badge></View><Text style={ui.muted}>{describeEventTiming(e)} · {e.isOnline?'온라인':e.location??'장소 미정'}</Text>{alsoOnDevice&&<Text style={{color:colors.green,fontWeight:'800'}}>✓ 기기 캘린더에도 추가됨</Text>}{conflict?.approximate?<Text style={{color:colors.red,fontWeight:'900'}}>⚠ 같은 기간에 기존 일정 {conflict.count}개 있음 · 시간 단위 충돌은 계산하지 않음</Text>:conflict&&conflict.minutes>0?<Text style={{color:colors.red,fontWeight:'900'}}>⚠ 기존 일정과 약 {conflict.minutes>=60?`${Math.floor(conflict.minutes/60)}시간${conflict.minutes%60?` ${conflict.minutes%60}분`:''}`:`${conflict.minutes}분`} 겹쳐요</Text>:null}</Card>})}
    {dayDevice.map(e=><Card key={`g-${e.id}`}><View style={{flexDirection:'row',justifyContent:'space-between',gap:8}}><Text style={[ui.h2,{flex:1}]}>{e.title}</Text><Badge>{e.calendarTitle}</Badge></View><Text style={ui.muted}>{formatTime(e.startDate,e.allDay)}{!e.allDay?` ~ ${formatTime(e.endDate)}`:''}</Text></Card>)}
  </Page>;
}
