import { useLocalSearchParams, router } from 'expo-router';
import { Linking, Pressable, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { Badge, Button, ErrorBox, Loading, Page, SectionTitle } from '@/components/Ui';
import { useNewsItem } from '@/api/hooks';
import { colors } from '@/theme';

function formatDate(value:string|null){if(!value)return null;const d=new Date(value);return Number.isNaN(d.getTime())?null:d.toLocaleDateString('ko-KR',{year:'numeric',month:'long',day:'numeric'})}

export default function AiNewsDetail(){
 const {width}=useWindowDimensions();const compact=width<370;const {id}=useLocalSearchParams<{id:string}>();const q=useNewsItem(id);
 if(q.isLoading)return <Page><Loading/></Page>;if(q.error||!q.data)return <Page><ErrorBox message={q.error?.message??'AI 뉴스를 찾을 수 없습니다.'}/></Page>;
 const item=q.data;const ready=Boolean(item.summary);const published=formatDate(item.publishedAt);
 return <Page>
  <View style={styles.topbar}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.topTitle}>AI 뉴스</Text><Pressable onPress={()=>Linking.openURL(item.url)} style={styles.open}><Text style={styles.openText}>▶</Text></Pressable></View>
  <View style={[styles.hero,compact&&styles.heroCompact]}><View style={styles.metaRow}><Badge tone="purple">{item.channel}</Badge><Badge tone={ready?'green':'orange'}>{ready?'약 3분 읽기':'요약 준비 중'}</Badge></View><Text style={[styles.title,compact&&{fontSize:27,lineHeight:34}]}>{item.title}</Text><Text style={styles.date}>{published??'최근 업로드'}</Text><View style={styles.heroLine}/><Text style={styles.heroHint}>영상 전체를 보지 않아도 흐름과 의미를 먼저 이해할 수 있게 정리합니다.</Text></View>
  {ready?<><SectionTitle title="이번 영상 한눈에 보기" subtitle="맥락과 의미까지 연결한 요약"/><Text style={styles.summary}>{item.summary}</Text>{item.highlights.length>0?<><View style={styles.divider}/><SectionTitle title="핵심 포인트"/><View style={styles.highlightList}>{item.highlights.map((x,i)=><View key={`${i}-${x}`} style={styles.highlightRow}><View style={styles.number}><Text style={styles.numberText}>{String(i+1).padStart(2,'0')}</Text></View><Text style={styles.highlightText}>{x}</Text></View>)}</View></>:null}</>:<View style={styles.pending}><Text style={styles.pendingEyebrow}>PROCESSING</Text><Text style={styles.pendingTitle}>요약을 만들고 있어요.</Text><Text style={styles.pendingBody}>자막을 우선 확인하고, 자막이 없으면 영상 설명과 챕터를 기반으로 내용을 정리합니다. 이 화면은 자동으로 다시 확인합니다.</Text><Button label={q.isFetching?'확인 중…':'지금 다시 확인'} variant="secondary" disabled={q.isFetching} onPress={()=>void q.refetch()}/></View>}
  <Button label="YouTube에서 원본 보기" onPress={()=>void Linking.openURL(item.url)}/>
 </Page>
}

const styles=StyleSheet.create({topbar:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},backText:{color:colors.text,fontSize:29,lineHeight:31},topTitle:{color:colors.text,fontSize:14,fontWeight:'900'},open:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},openText:{color:colors.accent,fontSize:13,fontWeight:'900'},hero:{backgroundColor:'#EFEAFF',borderRadius:28,padding:20,minHeight:245,gap:11},heroCompact:{padding:17,borderRadius:24,minHeight:230},metaRow:{flexDirection:'row',flexWrap:'wrap',gap:6},title:{color:colors.text,fontSize:31,lineHeight:39,fontWeight:'900',letterSpacing:-1},date:{color:colors.muted,fontSize:11,fontWeight:'700'},heroLine:{height:1,backgroundColor:'#DBD1FF',marginTop:'auto'},heroHint:{color:'#625A79',fontSize:11,lineHeight:17},summary:{color:colors.text,fontSize:17,lineHeight:29,fontWeight:'500'},divider:{height:1,backgroundColor:colors.line},highlightList:{backgroundColor:colors.surface,borderRadius:22,borderWidth:1,borderColor:colors.line,overflow:'hidden'},highlightRow:{flexDirection:'row',gap:12,padding:15,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line,alignItems:'flex-start'},number:{width:30,height:30,borderRadius:10,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center',flexShrink:0},numberText:{color:colors.accentDark,fontSize:10,fontWeight:'900'},highlightText:{color:'#4F4F59',fontSize:14,lineHeight:22,flex:1},pending:{backgroundColor:colors.surface,borderRadius:24,borderWidth:1,borderColor:colors.line,padding:18,gap:9},pendingEyebrow:{color:colors.orange,fontSize:9,fontWeight:'900',letterSpacing:1.6},pendingTitle:{color:colors.text,fontSize:20,fontWeight:'900'},pendingBody:{color:colors.muted,fontSize:13,lineHeight:21,marginBottom:5}});
