import { useLocalSearchParams, router } from 'expo-router';
import { Alert, Linking, Pressable, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { Badge, Button, Card, ErrorBox, Loading, Page, SectionTitle } from '@/components/Ui';
import { useEvent, useSetEventStatus } from '@/api/hooks';
import { colors, radius } from '@/theme';
import { addDeadlineWithSystemForm, addEventWithSystemForm, eventDateLabel, eventPrecision, findConflictsForEvent, isDateOnlyValue, type EventConflict } from '@/calendar';

function conflictText(conflicts:EventConflict[]){const top=conflicts.slice(0,3).map(x=>x.approximate?`• ${x.item.title} · 같은 기간에 일정 있음`:`• ${x.item.title} · ${x.minutes>=60?`${Math.floor(x.minutes/60)}시간${x.minutes%60?` ${x.minutes%60}분`:''}`:`${x.minutes}분`} 겹침`).join('\n');return `기존 캘린더 일정과 겹칩니다.\n\n${top}${conflicts.length>3?`\n외 ${conflicts.length-3}개`:''}`;}
function deadlineText(value:string){if(isDateOnlyValue(value))return new Date(`${value.slice(0,10)}T12:00:00`).toLocaleDateString('ko-KR');const d=new Date(value);return Number.isNaN(d.getTime())?'마감일 확인 필요':d.toLocaleString('ko-KR');}

export default function EventDetail(){
 const {width}=useWindowDimensions();const compact=width<370;const {id}=useLocalSearchParams<{id:string}>();const q=useEvent(id);const m=useSetEventStatus(id);
 if(q.isLoading)return <Page><Loading/></Page>;if(q.error||!q.data)return <Page><ErrorBox message={q.error?.message??'행사를 찾을 수 없습니다.'}/></Page>;
 const e=q.data;const exact=eventPrecision(e)==='EXACT';
 const calendarAdd=async(kind:'event'|'deadline'|'both')=>{try{if(kind==='event'||kind==='both')await addEventWithSystemForm(e);if((kind==='deadline'||kind==='both')&&e.deadline)await addDeadlineWithSystemForm(e)}catch(err){Alert.alert('캘린더 추가 실패',err instanceof Error?err.message:'캘린더 작성 화면을 열지 못했습니다.')}};
 const afterPlanning=()=>{if(!exact){Alert.alert('참가 예정으로 저장했어요',`${eventDateLabel(e)}으로 안내된 일정이라 정확한 날짜 공개 전까지 자동 충돌 계산과 행사 일정 추가는 하지 않습니다.`);return;}Alert.alert('참가 예정으로 저장했어요','휴대폰 캘린더에도 추가할까요?',[{text:'나중에',style:'cancel'},{text:'행사 일정',onPress:()=>void calendarAdd('event')},{text:e.deadline?'행사 + 마감':'캘린더 추가',onPress:()=>void calendarAdd(e.deadline?'both':'event')}])};
 const savePlanning=async()=>{try{await m.mutateAsync('PLANNING');afterPlanning()}catch(err){Alert.alert('저장 실패',err instanceof Error?err.message:'다시 시도해주세요.')}};
 const planning=async()=>{if(!exact){await savePlanning();return;}try{const conflicts=await findConflictsForEvent(e,true);if(conflicts.length){Alert.alert('일정이 겹쳐요',conflictText(conflicts),[{text:'취소',style:'cancel'},{text:'일정 보기',onPress:()=>router.push('/schedule')},{text:'그래도 참가',onPress:()=>void savePlanning()}]);return;}await savePlanning()}catch{Alert.alert('캘린더 확인 실패','기기 캘린더 일부를 읽지 못했습니다.',[{text:'취소',style:'cancel'},{text:'일정 탭',onPress:()=>router.push('/schedule')},{text:'그래도 참가',onPress:()=>void savePlanning()}])}};
 const check=async()=>{if(!exact){Alert.alert('정확한 날짜 미정',`${eventDateLabel(e)}으로만 안내되어 있어 지금은 충돌을 계산하지 않습니다.`);return;}try{const conflicts=await findConflictsForEvent(e,true);Alert.alert(conflicts.length?'일정 충돌 발견':'겹치는 일정 없음',conflicts.length?conflictText(conflicts):'현재 읽을 수 있는 휴대폰 캘린더 기준으로 겹치는 일정이 없습니다.')}catch{Alert.alert('확인 실패','일정 탭에서 캘린더 권한과 동기화 상태를 확인해주세요.')}};
 const status=e.userStatus;
 return <Page>
  <View style={styles.topbar}><Pressable onPress={()=>router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.topTitle}>행사 상세</Text><Pressable onPress={()=>Linking.openURL(e.sourceUrl)} style={styles.open}><Text style={styles.openText}>↗</Text></Pressable></View>
  <View style={[styles.hero,compact&&styles.heroCompact]}><View style={styles.tags}>{e.categories.slice(0,3).map(c=><Badge tone="purple" key={c}>{c}</Badge>)}</View><Text style={[styles.title,compact&&{fontSize:27,lineHeight:34}]}>{e.title}</Text><Text style={styles.date}>{eventDateLabel(e)}{!exact?' · 날짜 미정':''}</Text><View style={styles.heroFooter}><View style={styles.heroMeta}><Text style={styles.heroLabel}>장소</Text><Text style={styles.heroValue}>{e.isOnline?'온라인':e.location??'확인 필요'}</Text></View><View style={styles.heroMeta}><Text style={styles.heroLabel}>참가비</Text><Text style={styles.heroValue}>{e.fee===0?'무료':e.fee==null?'확인 필요':`${e.fee.toLocaleString()}원`}</Text></View></View></View>

  <View style={styles.infoGrid}><View style={styles.infoTile}><Text style={styles.infoLabel}>신청 마감</Text><Text style={styles.infoValue}>{e.deadline?deadlineText(e.deadline):'별도 마감 없음'}</Text></View><View style={styles.infoTile}><Text style={styles.infoLabel}>고등학생</Text><Text style={styles.infoValue}>{e.highSchoolAllowed===true?'참가 가능':e.highSchoolAllowed===false?'참가 불가':'확인 필요'}</Text></View></View>

  {e.summary?<><SectionTitle title="이 행사는"/><Text style={styles.description}>{e.summary}</Text></>:null}

  <SectionTitle title="내 상태" subtitle="관심에서 신청까지 한 번에 바꿔요."/>
  <View style={styles.statusActions}><Pressable onPress={()=>m.mutate('INTERESTED')} style={[styles.statusButton,status==='INTERESTED'&&styles.statusActive]}><Text style={[styles.statusButtonText,status==='INTERESTED'&&styles.statusActiveText]}>관심</Text></Pressable><Pressable onPress={()=>void planning()} style={[styles.statusButton,status==='PLANNING'&&styles.statusActive]}><Text style={[styles.statusButtonText,status==='PLANNING'&&styles.statusActiveText]}>참가 예정</Text></Pressable><Pressable onPress={()=>m.mutate('APPLIED')} style={[styles.statusButton,status==='APPLIED'&&styles.statusActive]}><Text style={[styles.statusButtonText,status==='APPLIED'&&styles.statusActiveText]}>신청 완료</Text></Pressable></View>

  <SectionTitle title="캘린더" subtitle={exact?'휴대폰 일정과 비교하고 바로 추가할 수 있어요.':'정확한 날짜가 공개되면 행사 일정을 추가할 수 있어요.'}/>
  <Card><Button label={exact?'기존 일정과 겹치는지 확인':'날짜 상태 확인'} variant="secondary" onPress={()=>void check()}/>{exact?<Button label="행사 일정 추가" variant="ghost" onPress={()=>void calendarAdd('event')}/>:null}{e.deadline?<Button label="신청 마감 추가" variant="ghost" onPress={()=>void calendarAdd('deadline')}/>:null}<Button label="내 일정 열기" variant="ghost" onPress={()=>router.push('/schedule')}/></Card>
  <Button label="공식 홈페이지 열기" onPress={()=>Linking.openURL(e.sourceUrl)}/>
 </Page>
}

const styles=StyleSheet.create({topbar:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},back:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},backText:{color:colors.text,fontSize:29,lineHeight:31,fontWeight:'400'},topTitle:{color:colors.text,fontSize:14,fontWeight:'900'},open:{width:42,height:42,borderRadius:14,borderWidth:1,borderColor:colors.line,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},openText:{color:colors.accent,fontSize:17,fontWeight:'900'},hero:{backgroundColor:'#F0EBFF',borderRadius:28,padding:20,minHeight:235,gap:11},heroCompact:{padding:17,borderRadius:24,minHeight:225},tags:{flexDirection:'row',flexWrap:'wrap',gap:6},title:{color:colors.text,fontSize:31,lineHeight:38,fontWeight:'900',letterSpacing:-1},date:{color:colors.accentDark,fontSize:13,fontWeight:'800'},heroFooter:{marginTop:'auto',paddingTop:16,flexDirection:'row',gap:8},heroMeta:{flex:1,minWidth:0,backgroundColor:'#FFFFFFA8',borderRadius:15,padding:11},heroLabel:{color:colors.muted,fontSize:9,fontWeight:'800'},heroValue:{color:colors.text,fontSize:12,fontWeight:'900',marginTop:3},infoGrid:{flexDirection:'row',gap:8},infoTile:{flex:1,minWidth:0,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,borderRadius:17,padding:13},infoLabel:{color:colors.muted,fontSize:10,fontWeight:'700'},infoValue:{color:colors.text,fontSize:13,lineHeight:19,fontWeight:'900',marginTop:4},description:{color:'#4F4F59',fontSize:15,lineHeight:25,fontWeight:'500'},statusActions:{flexDirection:'row',gap:7},statusButton:{flex:1,minWidth:0,minHeight:45,borderRadius:14,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center',paddingHorizontal:6},statusActive:{backgroundColor:colors.accent,borderColor:colors.accent},statusButtonText:{color:colors.muted,fontSize:11,fontWeight:'900',textAlign:'center'},statusActiveText:{color:'#fff'}});
